apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    {{- include "todo-app.labels" . | nindent 4 }}
    environment: {{ .Values.global.environment }}
