apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secret-store
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
- backend
- recurring-task-service
- notification-service
- websocket-service
- audit-service
